### ISSUE TITLE
Demo stopped working.

### ISSUE THREAD

**Issue by AndrewGearhart** [wintersandroid/wunderground-forecast#3]
The demo linked from the description doesn't currently work.
http://wintersandroid.github.io/wunderground-forecast/components/wunderground-forecast/

**Comment by mwinters-stuff** [comment]
Thanks for spotting that, Seems that the iron-component-page has changed and needs a new file generated from the polymer command.

**Comment by mwinters-stuff** [comment]
Working now. :)
